language: node_js
cache:
  directories:
    - $HOME/.npm
notifications:
  email: false
node_js:
  - "11"
  - "10"
stages:
  - lint
  - test
  - name: build
    if: NOT (branch = master AND type = push)
  - name: release
    if: branch = master AND type = push
jobs:
  include:
    - stage: test
      name: "Tests"
      script: npm run test
    - stage: lint
      name: "Lint"
      script: npm run lint
    - stage: build
      name: "Build"
      script: npm run build
    - stage: release
      name: "Release"
      script: npm run build && npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
